### PR TITLE
Optimize Performance

### PR DESCRIPTION
**Pull request by jamestalmage**
Do not walk unreachable branches.

### CODE REVIEW

**Comment by zertosh** [comment]
Unreachable branches are already not visited by returning `false`, no?

**Comment by jamestalmage** [comment]
Before you return false, you are calling this:

```
recast.visit(path, VISITOR_METHODS)
```

Which revisits everything, including things you have already walked; like the current node, and the `test` child node.

You are correct that unreachable branches aren't being walked, but that's because you did a 
`path.replace` already, and that branch won't be there to walk when you call `recast.visit`, so I did oversell the optimization a bit.

However, what I'm doing is still better because it does not revisit the `test` node multiple times.

**Comment by zertosh** [comment]
Hmm, maybe I'm missing something, but I don't think the `test` nodes are being re-visited either. When I do a `path.replace`, `path` is replaced with the _reachable_ branch and then that's traversed. Looking at the code again, there is a bit of unnecessary traversal in `visitLogicalExp`. When `path` is replaced by a literal, it's not necessary to traverse that. So [this](https://github.com/zertosh/unreachable-branch-transform/blob/d0bf6e12f07b2d4677cca810e0c91a5820f7eddf/unreachableBranchTransformer.js#L34) and [that](https://github.com/zertosh/unreachable-branch-transform/blob/d0bf6e12f07b2d4677cca810e0c91a5820f7eddf/unreachableBranchTransformer.js#L48) lines are the only ones that aren't needed.

**Comment by jamestalmage** [comment]
no, you're right.

**Pull request closed without merging**
